# Generated by Django 2.2 on 2019-04-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190420_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='likes',
            new_name='purchased',
        ),
    ]
