# Generated by Django 2.2 on 2019-04-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ticket_type',
            field=models.CharField(choices=[('BG', 'Bug'), ('FT', 'Feature')], default='BG', max_length=2),
        ),
    ]
